### ISSUE TITLE
Return None for non-existing keys

### ISSUE THREAD

**Issue by carlos-sarmiento** [rnag/dotwiz#14]
#### Is your feature request related to a problem? Please describe.
I'm using dotwiz to access configuration parameters in an easier to read and write manner. Sometimes a parameter will be optional and won't be included. If I currently try to read an optional parameter, I'll get an `AttributeError`. 

#### Describe the solution you'd like
It would be great if I could tell dotwiz to return None for any non-existing key

#### Describe alternatives you've considered
I'm currently using `has_attr` but it is just adding bulk to the system

**Comment by rnag** [comment]
Hi @carlos-sarmiento , have had some time to look into this. I was wondering if creating a helper subclass like this works for you? If so, I can probably see if I could add a config field or an extension class for this in a future release.

```python3
from dotwiz import DotWiz


class DotWizWithDefault(DotWiz):
    def __getattr__(self, item: str, __get=DotWiz.__dict__.get):
        return __get(item, None)
```

Usage would be like so:

```python3
dw = DotWizWithDefault(my_key='test')

assert dw.my_key == 'test'
assert dw.another_key is None
```

**Comment by rnag** [comment]
Now that I'm thinking about it, I feel this could also be generalized a little bit, to accept a `default` or `default_factory` argument to the constructor method (in case that could be useful):

```python3
from dataclasses import MISSING
from typing import Callable, Any

from dotwiz import DotWiz


class DefaultDotWiz(DotWiz):
    __slots__ = (
        'default_factory',
    )

    # noinspection PyDefaultArgument
    def __init__(self,
                 input_dict={}, *,
                 _default=None,
                 _default_factory: Callable[[], Any] = MISSING,
                 __set=object.__setattr__,
                 **kwargs):
        DotWiz.__init__(self, input_dict, **kwargs)

        if _default_factory is MISSING:
            def _default_factory(_):
                return _default
        else:
            # noinspection PyDefaultArgument
            def _default_factory(item: str, _factory=_default_factory,
                                 _self_dict=self.__dict__):
                result = _self_dict[item] = _factory()
                return result

        # noinspection PyArgumentList
        __set(self, 'default_factory', _default_factory)

    # noinspection PyDefaultArgument
    def __getattr__(self, item, _dict=DotWiz.__dict__):
        if item in _dict:
            return _dict[item]
        return self.default_factory(item)


dw = DefaultDotWiz(_default_factory=list, my_key='test')

assert dw.my_key == 'test'

dw.Another_key.append(42)
assert dw.Another_key == [42]
```

**Comment by carlos-sarmiento** [comment]
This is exactly what I'm talking about. The first example seems simple enough to be powerful

**Comment by rnag** [comment]
I'm planning for a `v0.4.0` release, which adds a new helper function `set_default_for_missing_keys()`.

Usage would be like:

```python3
from dotwiz import DotWiz, set_default_for_missing_keys

set_default_for_missing_keys()

dw = DotWiz(hello='world!')
assert dw.hello == 'world!'
assert dw.world is None
```

**Comment by rnag** [comment]
This should be complete - added as part of [v0.4.0](https://github.com/rnag/dotwiz/compare/v0.3.1...v0.4.0)

**Comment by mhillebrand** [comment]
What if this were the default behavior—without having to import `set_default_for_missing_keys` or invoke `set_default_for_missing_keys()`?
